# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntNCImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='IntNCReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(default='QC-001', editable=False, max_length=250, verbose_name='document number')),
                ('doc_title', models.CharField(default='Interior Component Non-Conformance Worksheet', editable=False, max_length=250, verbose_name='document title')),
                ('report_number', models.CharField(default='auto', editable=False, max_length=250)),
                ('order_number', models.CharField(max_length=250)),
                ('vin', models.CharField(max_length=250, verbose_name='VIN')),
                ('build_number', models.CharField(max_length=250)),
                ('report_date', models.DateField()),
                ('issue_summary', models.TextField(verbose_name='non-conformance description')),
                ('location', models.CharField(choices=[('Road Test', 'Road Test'), ('Analysis Center', 'Analysis Center'), ('QZ Audit', 'QZ Audit'), ('Syncreon', 'Syncreon'), ('Rework', 'Rework'), ('Section Audit', 'Section Audit'), ('PVAL', 'PVAL'), ('Prufriegel Audit', 'Prufriegel Audit'), ('Assembly', 'Assembly')], max_length=250)),
                ('part', models.CharField(choices=[('Instrument Panel', 'Instrument Panel'), ('Center Console', 'Center Console'), ('Glove Box', 'Glove Box'), ('Center Console Parts Kit', 'Center Console Parts Kit'), ('Cover Leg Room', 'Cover Leg Room'), ('Bulk Part', 'Bulk Part'), ('Door Panel Left Front', 'Door Panel Left Front'), ('Door Panel Left Rear', 'Door Panel Left Rear'), ('Door Panel Right Front', 'Door Panel Right Front'), ('Door Panel Right Rear', 'Door Panel Right Rear')], max_length=250)),
                ('inspection', models.CharField(choices=[('3rd part containment (Lumbee)', '3rd part containment (Lumbee)'), ('Supplier direct containment (initiated by BMW)', 'Supplier direct containment (initiated by BMW)'), ('Self directed containment (initiated by DRX)', 'Self directed containment (initiated by DRX)')], max_length=250)),
                ('vehicle', models.CharField(choices=[('F-15', 'F-15'), ('F-16', 'F-16'), ('F-25', 'F-25'), ('F-26', 'F-26'), ('F-86', 'F-86')], max_length=250)),
                ('drive', models.CharField(choices=[('Left Hand Drive', 'Left Hand Drive'), ('Right Hand Drive', 'Right Hand Drive')], max_length=250)),
                ('shift', models.CharField(choices=[('A shift', 'A shift'), ('B shift', 'B shift')], max_length=250)),
                ('clean_build', models.CharField(blank=True, max_length=250)),
                ('reported_to', models.CharField(choices=[('David Bell', 'David Bell'), ('Jerrica Mitchell', 'Jerrica Mitchell')], max_length=250)),
                ('repaired', models.BooleanField()),
                ('part_returned', models.BooleanField()),
                ('BI_level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=250)),
                ('in_PCSQ', models.BooleanField()),
                ('qn_num', models.CharField(blank=True, max_length=250)),
                ('accepts', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Under Investigation', 'Under Investigation')], default='Under Investigation', max_length=250)),
                ('containment', models.BooleanField()),
                ('quality_alert', models.BooleanField()),
                ('containment_activity', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('internal_rep', models.CharField(max_length=250)),
                ('external_rep', models.CharField(max_length=250)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IntNCReportBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50, verbose_name='VIN')),
                ('report_number', models.CharField(max_length=50)),
                ('report_date', models.DateField()),
                ('issue_summary', models.TextField()),
                ('issue_image_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='intncimage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcforms.IntNCReport'),
        ),
    ]
