# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntNCReportBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50, verbose_name='VIN')),
                ('report_number', models.CharField(max_length=50)),
                ('report_date', models.DateField()),
                ('issue_summary', models.TextField()),
                ('issue_image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50)),
                ('document_title', models.CharField(max_length=50)),
            ],
        ),
    ]
