# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 21:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intncreport',
            name='report_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
