# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntNCImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='ReportBasic',
        ),
        migrations.AddField(
            model_name='intncreport',
            name='BI_level',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], max_length=250),
        ),
        migrations.AddField(
            model_name='intncreport',
            name='accepts',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='intncreport',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intncreport',
            name='build_number',
            field=models.CharField(default='NONUM', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='clean_build',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='intncreport',
            name='containment',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='containment_activity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intncreport',
            name='drive',
            field=models.CharField(choices=[('LHD', 'Left Hand Drive'), ('RHD', 'Right Hand Drive')], default='NODRIVE', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='external_rep',
            field=models.CharField(default='NOREP', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='in_PCSQ',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='inspection',
            field=models.CharField(choices=[('LUMBEE', '3rd part containment'), ('BMW', 'Supplier direct containment (initiated by BMW)'), ('DRX', 'Self directed containment (initiated by DRX)')], default='NOINSPECT', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='internal_rep',
            field=models.CharField(default='NOREP', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='issue_summary',
            field=models.TextField(default='NOSUMMARY', verbose_name='non-conformance description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='location',
            field=models.CharField(choices=[('ROADTEST', 'Road Test'), ('ANALYSISCENTER', 'Analysis Center'), ('QCAUDIT', 'QZ Audit'), ('SYNCREON', 'Syncreon'), ('REWORK', 'Rework'), ('SECTIONAUDIT', 'Section Audit'), ('PVAL', 'PVAL'), ('PRUFRIEGEL', 'Prufriegel Audit'), ('ASSEMBLY', 'Assembly')], default='NOLOCATION', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='part',
            field=models.CharField(choices=[('IP', 'Instrument Panel'), ('CC', 'Center Console'), ('GB', 'Glove Box'), ('CCPK', 'Center Console Parts Kit'), ('CLR', 'Cover Leg Room'), ('BP', 'Bulk Part'), ('DPLF', 'Door Panel Left Front'), ('DPLR', 'Door Panel Left Rear'), ('DPRF', 'Door Panel Right Front'), ('DPRR', 'Door Panel Right Rear')], default='NOPART', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='part_returned',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='qn_num',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='intncreport',
            name='quality_alert',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='repaired',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='report_date',
            field=models.DateField(default=datetime.date(2016, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='reported_to',
            field=models.CharField(choices=[('DBELL', 'David Bell'), ('JMITCHELL', 'Jerrica Mitchell')], default='NOMANAGER', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='shift',
            field=models.CharField(choices=[('A', 'A shift'), ('B', 'B shift')], default='NOSHIFT', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='vehicle',
            field=models.CharField(choices=[('F15', 'F-15'), ('F16', 'F-16'), ('F25', 'F-25'), ('F26', 'F-26'), ('F86', 'F-86')], default='NOVEHICLE', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intncreport',
            name='vin',
            field=models.CharField(default='NOVIN', max_length=250, verbose_name='VIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='doc_number',
            field=models.CharField(default='QC-001', editable=False, max_length=250, verbose_name='document number'),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='doc_title',
            field=models.CharField(default='Interior Component Non-Conformance Worksheet', editable=False, max_length=250, verbose_name='document title'),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='order_number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='report_number',
            field=models.CharField(default='auto', editable=False, max_length=250),
        ),
        migrations.AddField(
            model_name='intncimage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcforms.IntNCReport'),
        ),
    ]
