# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import qcforms.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntNCReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(default='QC-001', editable=False, max_length=10, verbose_name='document number')),
                ('doc_title', models.CharField(default='Interior Component Non-Conformance Worksheet', editable=False, max_length=50, verbose_name='document title')),
                ('report_number', models.CharField(default=qcforms.models.IntNCReport.gen_report_num, editable=False, max_length=20)),
                ('order_number', models.CharField(max_length=20)),
            ],
        ),
    ]
