# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcforms', '0002_auto_20160408_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntNCReportBasic',
        ),
    ]
