# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import qcforms.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcforms', '0002_intncreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intncreport',
            name='doc_number',
            field=models.CharField(default='QC-001', editable=False, max_length=50, verbose_name='document number'),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='report_number',
            field=models.CharField(default=qcforms.models.IntNCReport.gen_report_num, editable=False, max_length=50),
        ),
    ]
