# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcforms', '0002_auto_20160408_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='intncreport',
            name='resolved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='accepts',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Under Investigation')], default='UNK', max_length=250),
        ),
    ]
