# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcforms', '0003_delete_intncreportbasic'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(default='QC-002', editable=False, max_length=250, verbose_name='document number')),
                ('doc_title', models.CharField(default='Quality Alert', editable=False, max_length=250, verbose_name='document title')),
                ('report_number', models.CharField(default='auto', editable=False, max_length=250)),
                ('alert_date', models.DateField(default=datetime.date.today)),
                ('issued_by', models.CharField(blank=True, max_length=250)),
                ('report_text', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('intncreport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qcforms.IntNCReport')),
            ],
        ),
    ]
