# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcforms', '0003_auto_20160408_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intncreport',
            name='BI_level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=250),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='accepts',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Under Investigation', 'Under Investigation')], default='Under Investigation', max_length=250),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='drive',
            field=models.CharField(choices=[('Left Hand Drive', 'Left Hand Drive'), ('Right Hand Drive', 'Right Hand Drive')], max_length=250),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='inspection',
            field=models.CharField(choices=[('3rd part containment (Lumbee)', '3rd part containment (Lumbee)'), ('Supplier direct containment (initiated by BMW)', 'Supplier direct containment (initiated by BMW)'), ('Self directed containment (initiated by DRX)', 'Self directed containment (initiated by DRX)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='location',
            field=models.CharField(choices=[('Road Test', 'Road Test'), ('Analysis Center', 'Analysis Center'), ('QZ Audit', 'QZ Audit'), ('Syncreon', 'Syncreon'), ('Rework', 'Rework'), ('Section Audit', 'Section Audit'), ('PVAL', 'PVAL'), ('Prufriegel Audit', 'Prufriegel Audit'), ('Assembly', 'Assembly')], max_length=250),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='part',
            field=models.CharField(choices=[('Instrument Panel', 'Instrument Panel'), ('Center Console', 'Center Console'), ('Glove Box', 'Glove Box'), ('Center Console Parts Kit', 'Center Console Parts Kit'), ('Cover Leg Room', 'Cover Leg Room'), ('Bulk Part', 'Bulk Part'), ('Door Panel Left Front', 'Door Panel Left Front'), ('Door Panel Left Rear', 'Door Panel Left Rear'), ('Door Panel Right Front', 'Door Panel Right Front'), ('Door Panel Right Rear', 'Door Panel Right Rear')], max_length=250),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='reported_to',
            field=models.CharField(choices=[('David Bell', 'David Bell'), ('Jerrica Mitchell', 'Jerrica Mitchell')], max_length=250),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='shift',
            field=models.CharField(choices=[('A shift', 'A shift'), ('B shift', 'B shift')], max_length=250),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='vehicle',
            field=models.CharField(choices=[('F-15', 'F-15'), ('F-16', 'F-16'), ('F-25', 'F-25'), ('F-26', 'F-26'), ('F-86', 'F-86')], max_length=250),
        ),
    ]
