# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcforms', '0003_auto_20160407_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intncreport',
            name='doc_title',
            field=models.CharField(default='Interior Component Non-Conformance Worksheet', editable=False, max_length=100, verbose_name='document title'),
        ),
        migrations.AlterField(
            model_name='intncreport',
            name='report_number',
            field=models.CharField(default='auto', editable=False, max_length=50),
        ),
    ]
