# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcforms', '0004_auto_20160408_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intncreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
