# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcforms', '0004_qualityalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intncreport',
            name='quality_alert',
        ),
        migrations.AlterField(
            model_name='qualityalert',
            name='intncreport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='qcforms.IntNCReport'),
        ),
    ]
